version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app:/usr/src/app
    command: sh -c "cd trellis && yarn && yarn start"
    ports:
      - "3000:3000"
