version: 2.1

executors:
  frontend-executor:
    docker:
      - image: circleci/node:14.16-stretch-browsers

references:
  cache_key: &cache_key v2-dependencies-{{ checksum "app/trellis/yarn.lock" }}
  save_node_modules: &save_node_modules
    save_cache:
      paths:
        - "app/trellis/node_modules"
      key: *cache_key
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *cache_key
  app_dir: &app_dir app/trellis

workflows:
  version: 2
  all-check:
    jobs:
      - package-install
      - build:
          requires:
            - package-install
      # - test:
      #     requires:
      #       - package-install

jobs:
  package-install:
    executor: frontend-executor
    steps:
      - checkout
      - *restore_node_modules
      - run:
          working_directory: *app_dir
          command: yarn install
      - *save_node_modules
  build:
    executor: frontend-executor
    steps:
      - checkout
      - *restore_node_modules
      - *save_node_modules
      - run:
          working_directory: *app_dir
          command: yarn build
  test:
    executor: frontend-executor
    steps:
      - checkout
      - *restore_node_modules
      - *save_node_modules
      - run:
          working_directory: *app_dir
          command: yarn test